# Generated by Django 5.2.1 on 2025-05-22 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at', '-updated_at'], 'verbose_name_plural': 'Posts'},
        ),
    ]
